### PR TITLE
Fix the URL patterns: ujoin() creates slashes.

### PR DESCRIPTION
**Pull request by afshin**
cc: @vidartf

### CODE REVIEW

**Comment by blink1073** [comment]
Thanks!

**Comment by vidartf** [comment]
Sorry for being slow here, I guess the ping doesn't hit when it's in an edit? Doesn't this make `/labrador` impossible again? I'd love that as a unit test 🐕

**Comment by afshin** [comment]
@vidartf Tornado respects the order that you added regular expressions to the launcher, so if you wanted `/labrador` you cann still just add that somewhere *before* the `NotFoundHandler`. Is that sufficient to the need you anticipate?

**Comment by vidartf** [comment]
Is it possible to make a given server extension load before another?

**Comment by afshin** [comment]
Let's talk about this tomorrow, I'm not sure what the answer is.

**Comment by blink1073** [comment]
They are loaded in alphabetical order

**Pull request merged**
