### PR TITLE
Fix path handling on Windows

### PR DESCRIPTION
**Pull request by blink1073**
cc @stonebig

### CODE REVIEW

**Comment by stonebig** [comment]
I uninstall jupyterlab_launcher-0.9.0 and installed jupyterlab_launcher-0.9.0.
Now jupyterlab starts but asks me to re-install plugins :
jupyterlabindex3

==>  is it expected ?

**Comment by stonebig** [comment]
I see un uglified error during build process:
````
ERROR in main.588f403504e6c2f38e8f.js from UglifyJs
Unexpected token: punc (,) [./~/jupyter-leaflet/src/jupyter-leaflet.js:528,30][main.588f403504e6c2f38e8f.js:180666,32]
Child html-webpack-plugin for "index.html":
    [3IRH] (webpack)/buildin/module.js 517 bytes {0} [built]
    [DuR2] (webpack)/buildin/global.js 509 bytes {0} [built]
    [GTAU] ./~/html-loader!./templates/partial.html 401 bytes {0} [built]
    [M4fF] ./~/lodash/lodash.js 540 kB {0} [built]
    [vxCX] ./~/html-webpack-plugin/lib/loader.js!./templates/template.html 1.6 kB {0} [built]
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
````

**Comment by stonebig** [comment]
now missing notebook-5.3.0 to have teminado working on windows.

**Comment by blink1073** [comment]
Not sure about the errors.  I'll come back to this after the holiday.

**Comment by stonebig** [comment]
These errors are gone after rebuilding everything. all looks ok now.

**Pull request merged**
